# Generated by Django 3.2.8 on 2021-10-31 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_sent',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request_sent',
            name='introducer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='introducer2', to=settings.AUTH_USER_MODEL),
        ),
    ]
