# Generated by Django 3.2.8 on 2021-10-28 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadharNo',
            field=models.BigIntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator('^[01]\\d{3}[\\s-]?\\d{4}[\\s-]?\\d{4}$')]),
        ),
    ]
