# Generated by Django 3.2.8 on 2021-10-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='aadhar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
