# Generated by Django 3.2.8 on 2021-10-31 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_sent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request_sent',
            name='introducer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_introducer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request_sent',
            name='status',
            field=models.CharField(default='empty', max_length=10),
        ),
    ]
