# Generated by Django 3.2.8 on 2021-10-31 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_request_sent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_confirm',
            name='adderss',
        ),
        migrations.AddField(
            model_name='request_confirm',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='backend.address'),
        ),
    ]
