# Generated by Django 3.2.8 on 2021-10-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(auto_created=True, max_length=255, unique=True),
        ),
    ]
