# Generated by Django 3.2.8 on 2021-10-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211031_1452'),
        ('backend', '0008_alter_request_sent_status'),
    ]

    operations = [
    ]
